# Generated by Django 4.1.1 on 2022-09-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categooria',
            new_name='categoria',
        ),
    ]
